// Mocks generated by Mockito 5.4.4 from annotations
// in ncm_mobile_app/test/features/members/pages/quick_registration_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ncm_mobile_app/data/models/user_model.dart' as _i3;
import 'package:ncm_mobile_app/providers/members_provider.dart' as _i4;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemberModel_1 extends _i1.SmartFake implements _i3.MemberModel {
  _FakeMemberModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MembersNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockMembersNotifier extends _i1.Mock implements _i4.MembersNotifier {
  MockMembersNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i2.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.AsyncValue<List<_i3.MemberModel>>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.AsyncValue<List<_i3.MemberModel>>>.empty(),
      ) as _i5.Stream<_i2.AsyncValue<List<_i3.MemberModel>>>);

  @override
  _i2.AsyncValue<List<_i3.MemberModel>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_0<List<_i3.MemberModel>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<List<_i3.MemberModel>>);

  @override
  set state(_i2.AsyncValue<List<_i3.MemberModel>>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AsyncValue<List<_i3.MemberModel>> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAsyncValue_0<List<_i3.MemberModel>>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.AsyncValue<List<_i3.MemberModel>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadMembers() => (super.noSuchMethod(
        Invocation.method(
          #loadMembers,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.MemberModel> createMember({
    required String? idNumber,
    required String? name,
    required String? surname,
    required DateTime? dateOfBirth,
    required String? gender,
    required String? phoneNumber,
    String? email,
    String? alternativePhone,
    required String? address,
    required String? suburb,
    required String? city,
    required String? postalCode,
    required String? ward,
    String? votingDistrict,
    int? municipalityId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMember,
          [],
          {
            #idNumber: idNumber,
            #name: name,
            #surname: surname,
            #dateOfBirth: dateOfBirth,
            #gender: gender,
            #phoneNumber: phoneNumber,
            #email: email,
            #alternativePhone: alternativePhone,
            #address: address,
            #suburb: suburb,
            #city: city,
            #postalCode: postalCode,
            #ward: ward,
            #votingDistrict: votingDistrict,
            #municipalityId: municipalityId,
          },
        ),
        returnValue: _i5.Future<_i3.MemberModel>.value(_FakeMemberModel_1(
          this,
          Invocation.method(
            #createMember,
            [],
            {
              #idNumber: idNumber,
              #name: name,
              #surname: surname,
              #dateOfBirth: dateOfBirth,
              #gender: gender,
              #phoneNumber: phoneNumber,
              #email: email,
              #alternativePhone: alternativePhone,
              #address: address,
              #suburb: suburb,
              #city: city,
              #postalCode: postalCode,
              #ward: ward,
              #votingDistrict: votingDistrict,
              #municipalityId: municipalityId,
            },
          ),
        )),
      ) as _i5.Future<_i3.MemberModel>);

  @override
  _i5.Future<_i3.MemberModel> getMember(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMember,
          [id],
        ),
        returnValue: _i5.Future<_i3.MemberModel>.value(_FakeMemberModel_1(
          this,
          Invocation.method(
            #getMember,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.MemberModel>);

  @override
  _i5.Future<_i3.MemberModel> updateMember(
    int? id,
    _i3.MemberModel? member,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMember,
          [
            id,
            member,
          ],
        ),
        returnValue: _i5.Future<_i3.MemberModel>.value(_FakeMemberModel_1(
          this,
          Invocation.method(
            #updateMember,
            [
              id,
              member,
            ],
          ),
        )),
      ) as _i5.Future<_i3.MemberModel>);

  @override
  List<_i3.MemberModel> searchMembers(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchMembers,
          [query],
        ),
        returnValue: <_i3.MemberModel>[],
      ) as List<_i3.MemberModel>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<List<_i3.MemberModel>>? old,
    _i2.AsyncValue<List<_i3.MemberModel>>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.RemoveListener addListener(
    _i6.Listener<_i2.AsyncValue<List<_i3.MemberModel>>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
