// Mocks generated by Mockito 5.4.4 from annotations
// in ncm_mobile_app/test/features/members/digital_membership_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ncm_mobile_app/core/services/api_service.dart' as _i2;
import 'package:ncm_mobile_app/data/models/complaint_model.dart' as _i6;
import 'package:ncm_mobile_app/data/models/poll_statistics_response.dart'
    as _i8;
import 'package:ncm_mobile_app/data/models/registration_models.dart' as _i4;
import 'package:ncm_mobile_app/data/models/supporter_model.dart' as _i11;
import 'package:ncm_mobile_app/data/models/user_model.dart' as _i3;
import 'package:ncm_mobile_app/data/models/visit_model.dart' as _i5;
import 'package:ncm_mobile_app/data/models/vote_submission_request.dart'
    as _i10;
import 'package:ncm_mobile_app/data/models/vote_submission_response.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponse_0 extends _i1.SmartFake implements _i2.AuthResponse {
  _FakeAuthResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_1 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckIdNumberResponse_2 extends _i1.SmartFake
    implements _i4.CheckIdNumberResponse {
  _FakeCheckIdNumberResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterMemberResponse_3 extends _i1.SmartFake
    implements _i4.RegisterMemberResponse {
  _FakeRegisterMemberResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVerifyRegistrationResponse_4 extends _i1.SmartFake
    implements _i4.VerifyRegistrationResponse {
  _FakeVerifyRegistrationResponse_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResendCodeResponse_5 extends _i1.SmartFake
    implements _i4.ResendCodeResponse {
  _FakeResendCodeResponse_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResponse_6<T> extends _i1.SmartFake
    implements _i2.PaginatedResponse<T> {
  _FakePaginatedResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMemberModel_7 extends _i1.SmartFake implements _i3.MemberModel {
  _FakeMemberModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFindMemberByMembershipNumberResponse_8 extends _i1.SmartFake
    implements _i2.FindMemberByMembershipNumberResponse {
  _FakeFindMemberByMembershipNumberResponse_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVisitModel_9 extends _i1.SmartFake implements _i5.VisitModel {
  _FakeVisitModel_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLeaderModel_10 extends _i1.SmartFake implements _i3.LeaderModel {
  _FakeLeaderModel_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVisitStatsModel_11 extends _i1.SmartFake
    implements _i5.VisitStatsModel {
  _FakeVisitStatsModel_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVisitNoteModel_12 extends _i1.SmartFake
    implements _i5.VisitNoteModel {
  _FakeVisitNoteModel_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComplaintModel_13 extends _i1.SmartFake
    implements _i6.ComplaintModel {
  _FakeComplaintModel_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeComplaintCategoryModel_14 extends _i1.SmartFake
    implements _i6.ComplaintCategoryModel {
  _FakeComplaintCategoryModel_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMunicipalityModel_15 extends _i1.SmartFake
    implements _i3.MunicipalityModel {
  _FakeMunicipalityModel_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQrCodeResponse_16 extends _i1.SmartFake
    implements _i2.QrCodeResponse {
  _FakeQrCodeResponse_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQrVerifyResponse_17 extends _i1.SmartFake
    implements _i2.QrVerifyResponse {
  _FakeQrVerifyResponse_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePollModel_18 extends _i1.SmartFake implements _i2.PollModel {
  _FakePollModel_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVoteSubmissionResponse_19 extends _i1.SmartFake
    implements _i7.VoteSubmissionResponse {
  _FakeVoteSubmissionResponse_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePollStatisticsWrapper_20 extends _i1.SmartFake
    implements _i8.PollStatisticsWrapper {
  _FakePollStatisticsWrapper_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCreateSupporterResponse_21 extends _i1.SmartFake
    implements _i2.CreateSupporterResponse {
  _FakeCreateSupporterResponse_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGetSupporterResponse_22 extends _i1.SmartFake
    implements _i2.GetSupporterResponse {
  _FakeGetSupporterResponse_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSupporterStatsResponse_23 extends _i1.SmartFake
    implements _i2.SupporterStatsResponse {
  _FakeSupporterStatsResponse_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSendSmsResponse_24 extends _i1.SmartFake
    implements _i2.SendSmsResponse {
  _FakeSendSmsResponse_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSmsStatsResponse_25 extends _i1.SmartFake
    implements _i2.SmsStatsResponse {
  _FakeSmsStatsResponse_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSmsLogModel_26 extends _i1.SmartFake implements _i2.SmsLogModel {
  _FakeSmsLogModel_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCheckSmsStatusResponse_27 extends _i1.SmartFake
    implements _i2.CheckSmsStatusResponse {
  _FakeCheckSmsStatusResponse_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePayFastConfigResponse_28 extends _i1.SmartFake
    implements _i2.PayFastConfigResponse {
  _FakePayFastConfigResponse_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePushNotificationResponse_29 extends _i1.SmartFake
    implements _i2.PushNotificationResponse {
  _FakePushNotificationResponse_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePushNotificationHistoryResponse_30 extends _i1.SmartFake
    implements _i2.PushNotificationHistoryResponse {
  _FakePushNotificationHistoryResponse_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePushNotificationStatsResponse_31 extends _i1.SmartFake
    implements _i2.PushNotificationStatsResponse {
  _FakePushNotificationStatsResponse_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventModel_32 extends _i1.SmartFake implements _i2.EventModel {
  _FakeEventModel_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventRegistrationResponse_33 extends _i1.SmartFake
    implements _i2.EventRegistrationResponse {
  _FakeEventRegistrationResponse_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFeedbackResponse_34 extends _i1.SmartFake
    implements _i2.FeedbackResponse {
  _FakeFeedbackResponse_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaymentResponse_35 extends _i1.SmartFake
    implements _i2.PaymentResponse {
  _FakePaymentResponse_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMembershipStatusResponse_36 extends _i1.SmartFake
    implements _i2.MembershipStatusResponse {
  _FakeMembershipStatusResponse_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i2.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.AuthResponse> login(_i2.MobileLoginRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [request],
        ),
        returnValue: _i9.Future<_i2.AuthResponse>.value(_FakeAuthResponse_0(
          this,
          Invocation.method(
            #login,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.AuthResponse>);

  @override
  _i9.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i3.UserModel> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i9.Future<_i3.UserModel>.value(_FakeUserModel_1(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i9.Future<_i3.UserModel>);

  @override
  _i9.Future<_i4.CheckIdNumberResponse> checkIdNumber(
          _i4.CheckIdNumberRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkIdNumber,
          [request],
        ),
        returnValue: _i9.Future<_i4.CheckIdNumberResponse>.value(
            _FakeCheckIdNumberResponse_2(
          this,
          Invocation.method(
            #checkIdNumber,
            [request],
          ),
        )),
      ) as _i9.Future<_i4.CheckIdNumberResponse>);

  @override
  _i9.Future<_i4.RegisterMemberResponse> registerMember(
          _i4.RegisterMemberRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerMember,
          [request],
        ),
        returnValue: _i9.Future<_i4.RegisterMemberResponse>.value(
            _FakeRegisterMemberResponse_3(
          this,
          Invocation.method(
            #registerMember,
            [request],
          ),
        )),
      ) as _i9.Future<_i4.RegisterMemberResponse>);

  @override
  _i9.Future<_i4.VerifyRegistrationResponse> verifyRegistration(
          _i4.VerifyRegistrationRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyRegistration,
          [request],
        ),
        returnValue: _i9.Future<_i4.VerifyRegistrationResponse>.value(
            _FakeVerifyRegistrationResponse_4(
          this,
          Invocation.method(
            #verifyRegistration,
            [request],
          ),
        )),
      ) as _i9.Future<_i4.VerifyRegistrationResponse>);

  @override
  _i9.Future<_i4.ResendCodeResponse> resendVerificationCode(
          _i4.ResendCodeRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerificationCode,
          [request],
        ),
        returnValue:
            _i9.Future<_i4.ResendCodeResponse>.value(_FakeResendCodeResponse_5(
          this,
          Invocation.method(
            #resendVerificationCode,
            [request],
          ),
        )),
      ) as _i9.Future<_i4.ResendCodeResponse>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i3.MemberModel>> getMembers(
    int? page,
    int? municipalityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembers,
          [
            page,
            municipalityId,
          ],
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i3.MemberModel>>.value(
            _FakePaginatedResponse_6<_i3.MemberModel>(
          this,
          Invocation.method(
            #getMembers,
            [
              page,
              municipalityId,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i3.MemberModel>>);

  @override
  _i9.Future<_i3.MemberModel> getMember(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMember,
          [id],
        ),
        returnValue: _i9.Future<_i3.MemberModel>.value(_FakeMemberModel_7(
          this,
          Invocation.method(
            #getMember,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.MemberModel>);

  @override
  _i9.Future<_i3.MemberModel> createMember(_i2.CreateMemberRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMember,
          [request],
        ),
        returnValue: _i9.Future<_i3.MemberModel>.value(_FakeMemberModel_7(
          this,
          Invocation.method(
            #createMember,
            [request],
          ),
        )),
      ) as _i9.Future<_i3.MemberModel>);

  @override
  _i9.Future<_i3.MemberModel> updateMember(
    int? id,
    _i2.UpdateMemberRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMember,
          [
            id,
            request,
          ],
        ),
        returnValue: _i9.Future<_i3.MemberModel>.value(_FakeMemberModel_7(
          this,
          Invocation.method(
            #updateMember,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i3.MemberModel>);

  @override
  _i9.Future<_i3.MemberModel> searchMember(String? idNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMember,
          [idNumber],
        ),
        returnValue: _i9.Future<_i3.MemberModel>.value(_FakeMemberModel_7(
          this,
          Invocation.method(
            #searchMember,
            [idNumber],
          ),
        )),
      ) as _i9.Future<_i3.MemberModel>);

  @override
  _i9.Future<List<_i3.MemberModel>> searchMembers(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMembers,
          [query],
        ),
        returnValue:
            _i9.Future<List<_i3.MemberModel>>.value(<_i3.MemberModel>[]),
      ) as _i9.Future<List<_i3.MemberModel>>);

  @override
  _i9.Future<_i2.FindMemberByMembershipNumberResponse>
      findMemberByMembershipNumber(String? membershipNumber) =>
          (super.noSuchMethod(
            Invocation.method(
              #findMemberByMembershipNumber,
              [membershipNumber],
            ),
            returnValue:
                _i9.Future<_i2.FindMemberByMembershipNumberResponse>.value(
                    _FakeFindMemberByMembershipNumberResponse_8(
              this,
              Invocation.method(
                #findMemberByMembershipNumber,
                [membershipNumber],
              ),
            )),
          ) as _i9.Future<_i2.FindMemberByMembershipNumberResponse>);

  @override
  _i9.Future<_i3.MemberModel> activateMemberAccount(
    int? id,
    _i2.ActivateMemberAccountRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #activateMemberAccount,
          [
            id,
            request,
          ],
        ),
        returnValue: _i9.Future<_i3.MemberModel>.value(_FakeMemberModel_7(
          this,
          Invocation.method(
            #activateMemberAccount,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i3.MemberModel>);

  @override
  _i9.Future<_i5.VisitModel> createVisitFromMembership(
          _i2.CreateVisitFromMembershipRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisitFromMembership,
          [request],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #createVisitFromMembership,
            [request],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i3.LeaderModel>> getLeaders(
    int? page,
    int? municipalityId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLeaders,
          [
            page,
            municipalityId,
          ],
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i3.LeaderModel>>.value(
            _FakePaginatedResponse_6<_i3.LeaderModel>(
          this,
          Invocation.method(
            #getLeaders,
            [
              page,
              municipalityId,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i3.LeaderModel>>);

  @override
  _i9.Future<_i3.LeaderModel> getLeader(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getLeader,
          [id],
        ),
        returnValue: _i9.Future<_i3.LeaderModel>.value(_FakeLeaderModel_10(
          this,
          Invocation.method(
            #getLeader,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.LeaderModel>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i5.VisitModel>> getVisits(
    int? page,
    int? leaderId,
    int? memberId,
    int? municipalityId,
    String? visitType,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisits,
          [
            page,
            leaderId,
            memberId,
            municipalityId,
            visitType,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i5.VisitModel>>.value(
            _FakePaginatedResponse_6<_i5.VisitModel>(
          this,
          Invocation.method(
            #getVisits,
            [
              page,
              leaderId,
              memberId,
              municipalityId,
              visitType,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i5.VisitModel>>);

  @override
  _i9.Future<_i5.VisitModel> createVisit(_i2.CreateVisitRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisit,
          [request],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #createVisit,
            [request],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<_i5.VisitModel> getVisit(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getVisit,
          [id],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #getVisit,
            [id],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<_i5.VisitModel> updateVisit(
    int? id,
    _i2.UpdateVisitRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateVisit,
          [
            id,
            request,
          ],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #updateVisit,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<_i5.VisitModel> assignVisit(
    int? id,
    _i2.AssignVisitRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignVisit,
          [
            id,
            request,
          ],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #assignVisit,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<_i5.VisitModel> checkInToVisit(
    int? id,
    _i2.CheckInRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkInToVisit,
          [
            id,
            request,
          ],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #checkInToVisit,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<_i5.VisitModel> checkOutFromVisit(
    int? id,
    _i2.CheckOutRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkOutFromVisit,
          [
            id,
            request,
          ],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #checkOutFromVisit,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<void> deleteVisit(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteVisit,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i5.VisitModel>> getVisitsByLeader(
    int? leaderId,
    int? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitsByLeader,
          [
            leaderId,
            page,
          ],
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i5.VisitModel>>.value(
            _FakePaginatedResponse_6<_i5.VisitModel>(
          this,
          Invocation.method(
            #getVisitsByLeader,
            [
              leaderId,
              page,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i5.VisitModel>>);

  @override
  _i9.Future<_i5.VisitStatsModel> getSentimentStats(
    int? municipalityId,
    int? leaderId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSentimentStats,
          [
            municipalityId,
            leaderId,
            startDate,
            endDate,
          ],
        ),
        returnValue:
            _i9.Future<_i5.VisitStatsModel>.value(_FakeVisitStatsModel_11(
          this,
          Invocation.method(
            #getSentimentStats,
            [
              municipalityId,
              leaderId,
              startDate,
              endDate,
            ],
          ),
        )),
      ) as _i9.Future<_i5.VisitStatsModel>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i5.VisitNoteModel>> getVisitNotes(
    int? page,
    int? visitId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVisitNotes,
          [
            page,
            visitId,
          ],
        ),
        returnValue:
            _i9.Future<_i2.PaginatedResponse<_i5.VisitNoteModel>>.value(
                _FakePaginatedResponse_6<_i5.VisitNoteModel>(
          this,
          Invocation.method(
            #getVisitNotes,
            [
              page,
              visitId,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i5.VisitNoteModel>>);

  @override
  _i9.Future<_i5.VisitNoteModel> createVisitNote(
          _i2.CreateVisitNoteRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisitNote,
          [request],
        ),
        returnValue:
            _i9.Future<_i5.VisitNoteModel>.value(_FakeVisitNoteModel_12(
          this,
          Invocation.method(
            #createVisitNote,
            [request],
          ),
        )),
      ) as _i9.Future<_i5.VisitNoteModel>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i6.ComplaintModel>> getComplaints(
    int? page,
    int? memberId,
    int? municipalityId,
    String? status,
    String? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComplaints,
          [
            page,
            memberId,
            municipalityId,
            status,
            priority,
          ],
        ),
        returnValue:
            _i9.Future<_i2.PaginatedResponse<_i6.ComplaintModel>>.value(
                _FakePaginatedResponse_6<_i6.ComplaintModel>(
          this,
          Invocation.method(
            #getComplaints,
            [
              page,
              memberId,
              municipalityId,
              status,
              priority,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i6.ComplaintModel>>);

  @override
  _i9.Future<_i6.ComplaintModel> createComplaint(
          _i2.CreateComplaintRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createComplaint,
          [request],
        ),
        returnValue:
            _i9.Future<_i6.ComplaintModel>.value(_FakeComplaintModel_13(
          this,
          Invocation.method(
            #createComplaint,
            [request],
          ),
        )),
      ) as _i9.Future<_i6.ComplaintModel>);

  @override
  _i9.Future<_i6.ComplaintModel> getComplaint(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getComplaint,
          [id],
        ),
        returnValue:
            _i9.Future<_i6.ComplaintModel>.value(_FakeComplaintModel_13(
          this,
          Invocation.method(
            #getComplaint,
            [id],
          ),
        )),
      ) as _i9.Future<_i6.ComplaintModel>);

  @override
  _i9.Future<_i6.ComplaintModel> updateComplaint(
    int? id,
    _i2.UpdateComplaintRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateComplaint,
          [
            id,
            request,
          ],
        ),
        returnValue:
            _i9.Future<_i6.ComplaintModel>.value(_FakeComplaintModel_13(
          this,
          Invocation.method(
            #updateComplaint,
            [
              id,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i6.ComplaintModel>);

  @override
  _i9.Future<List<_i6.ComplaintCategoryModel>> getComplaintCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getComplaintCategories,
          [],
        ),
        returnValue: _i9.Future<List<_i6.ComplaintCategoryModel>>.value(
            <_i6.ComplaintCategoryModel>[]),
      ) as _i9.Future<List<_i6.ComplaintCategoryModel>>);

  @override
  _i9.Future<_i6.ComplaintCategoryModel> getComplaintCategory(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getComplaintCategory,
          [id],
        ),
        returnValue: _i9.Future<_i6.ComplaintCategoryModel>.value(
            _FakeComplaintCategoryModel_14(
          this,
          Invocation.method(
            #getComplaintCategory,
            [id],
          ),
        )),
      ) as _i9.Future<_i6.ComplaintCategoryModel>);

  @override
  _i9.Future<List<_i3.MunicipalityModel>> getMunicipalities() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMunicipalities,
          [],
        ),
        returnValue: _i9.Future<List<_i3.MunicipalityModel>>.value(
            <_i3.MunicipalityModel>[]),
      ) as _i9.Future<List<_i3.MunicipalityModel>>);

  @override
  _i9.Future<_i3.MunicipalityModel> getMunicipality(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMunicipality,
          [id],
        ),
        returnValue:
            _i9.Future<_i3.MunicipalityModel>.value(_FakeMunicipalityModel_15(
          this,
          Invocation.method(
            #getMunicipality,
            [id],
          ),
        )),
      ) as _i9.Future<_i3.MunicipalityModel>);

  @override
  _i9.Future<_i2.QrCodeResponse> generateMemberQrCode(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateMemberQrCode,
          [id],
        ),
        returnValue:
            _i9.Future<_i2.QrCodeResponse>.value(_FakeQrCodeResponse_16(
          this,
          Invocation.method(
            #generateMemberQrCode,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.QrCodeResponse>);

  @override
  _i9.Future<_i2.QrVerifyResponse> verifyQrCode(_i2.QrVerifyRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyQrCode,
          [request],
        ),
        returnValue:
            _i9.Future<_i2.QrVerifyResponse>.value(_FakeQrVerifyResponse_17(
          this,
          Invocation.method(
            #verifyQrCode,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.QrVerifyResponse>);

  @override
  _i9.Future<_i5.VisitModel> createVisitFromQr(
          _i2.QrCreateVisitRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisitFromQr,
          [request],
        ),
        returnValue: _i9.Future<_i5.VisitModel>.value(_FakeVisitModel_9(
          this,
          Invocation.method(
            #createVisitFromQr,
            [request],
          ),
        )),
      ) as _i9.Future<_i5.VisitModel>);

  @override
  _i9.Future<List<_i2.PollModel>> getPolls(
    int? page,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPolls,
          [
            page,
            status,
          ],
        ),
        returnValue: _i9.Future<List<_i2.PollModel>>.value(<_i2.PollModel>[]),
      ) as _i9.Future<List<_i2.PollModel>>);

  @override
  _i9.Future<_i2.PollModel> getPollDetails(int? pollId) => (super.noSuchMethod(
        Invocation.method(
          #getPollDetails,
          [pollId],
        ),
        returnValue: _i9.Future<_i2.PollModel>.value(_FakePollModel_18(
          this,
          Invocation.method(
            #getPollDetails,
            [pollId],
          ),
        )),
      ) as _i9.Future<_i2.PollModel>);

  @override
  _i9.Future<_i7.VoteSubmissionResponse> submitVote(
    int? pollId,
    _i10.VoteSubmissionRequest? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitVote,
          [
            pollId,
            request,
          ],
        ),
        returnValue: _i9.Future<_i7.VoteSubmissionResponse>.value(
            _FakeVoteSubmissionResponse_19(
          this,
          Invocation.method(
            #submitVote,
            [
              pollId,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i7.VoteSubmissionResponse>);

  @override
  _i9.Future<_i8.PollStatisticsWrapper> getPollStatistics(int? pollId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPollStatistics,
          [pollId],
        ),
        returnValue: _i9.Future<_i8.PollStatisticsWrapper>.value(
            _FakePollStatisticsWrapper_20(
          this,
          Invocation.method(
            #getPollStatistics,
            [pollId],
          ),
        )),
      ) as _i9.Future<_i8.PollStatisticsWrapper>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i2.AnnouncementModel>> getAnnouncements(
    int? page,
    String? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnnouncements,
          [
            page,
            priority,
          ],
        ),
        returnValue:
            _i9.Future<_i2.PaginatedResponse<_i2.AnnouncementModel>>.value(
                _FakePaginatedResponse_6<_i2.AnnouncementModel>(
          this,
          Invocation.method(
            #getAnnouncements,
            [
              page,
              priority,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i2.AnnouncementModel>>);

  @override
  _i9.Future<void> markAnnouncementAsRead(int? announcementId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAnnouncementAsRead,
          [announcementId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i11.SupporterModel>> getSupporters(
    int? page,
    String? ward,
    String? registeredVoter,
    String? search,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupporters,
          [
            page,
            ward,
            registeredVoter,
            search,
          ],
        ),
        returnValue:
            _i9.Future<_i2.PaginatedResponse<_i11.SupporterModel>>.value(
                _FakePaginatedResponse_6<_i11.SupporterModel>(
          this,
          Invocation.method(
            #getSupporters,
            [
              page,
              ward,
              registeredVoter,
              search,
            ],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i11.SupporterModel>>);

  @override
  _i9.Future<_i2.CreateSupporterResponse> createSupporter(
          _i2.CreateSupporterRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSupporter,
          [request],
        ),
        returnValue: _i9.Future<_i2.CreateSupporterResponse>.value(
            _FakeCreateSupporterResponse_21(
          this,
          Invocation.method(
            #createSupporter,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.CreateSupporterResponse>);

  @override
  _i9.Future<_i2.GetSupporterResponse> getSupporter(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupporter,
          [id],
        ),
        returnValue: _i9.Future<_i2.GetSupporterResponse>.value(
            _FakeGetSupporterResponse_22(
          this,
          Invocation.method(
            #getSupporter,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.GetSupporterResponse>);

  @override
  _i9.Future<_i2.SupporterStatsResponse> getSupporterStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getSupporterStats,
          [],
        ),
        returnValue: _i9.Future<_i2.SupporterStatsResponse>.value(
            _FakeSupporterStatsResponse_23(
          this,
          Invocation.method(
            #getSupporterStats,
            [],
          ),
        )),
      ) as _i9.Future<_i2.SupporterStatsResponse>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i2.SmsLogModel>> getSmsLogs(
    int? page, {
    String? status,
    String? dateFrom,
    String? dateTo,
    String? search,
    int? perPage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmsLogs,
          [page],
          {
            #status: status,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
            #search: search,
            #perPage: perPage,
          },
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i2.SmsLogModel>>.value(
            _FakePaginatedResponse_6<_i2.SmsLogModel>(
          this,
          Invocation.method(
            #getSmsLogs,
            [page],
            {
              #status: status,
              #dateFrom: dateFrom,
              #dateTo: dateTo,
              #search: search,
              #perPage: perPage,
            },
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i2.SmsLogModel>>);

  @override
  _i9.Future<_i2.SendSmsResponse> sendSms(_i2.SendSmsRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendSms,
          [request],
        ),
        returnValue:
            _i9.Future<_i2.SendSmsResponse>.value(_FakeSendSmsResponse_24(
          this,
          Invocation.method(
            #sendSms,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.SendSmsResponse>);

  @override
  _i9.Future<_i2.SmsStatsResponse> getSmsStats({
    String? dateFrom,
    String? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSmsStats,
          [],
          {
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue:
            _i9.Future<_i2.SmsStatsResponse>.value(_FakeSmsStatsResponse_25(
          this,
          Invocation.method(
            #getSmsStats,
            [],
            {
              #dateFrom: dateFrom,
              #dateTo: dateTo,
            },
          ),
        )),
      ) as _i9.Future<_i2.SmsStatsResponse>);

  @override
  _i9.Future<_i2.SmsLogModel> getSmsLog(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getSmsLog,
          [id],
        ),
        returnValue: _i9.Future<_i2.SmsLogModel>.value(_FakeSmsLogModel_26(
          this,
          Invocation.method(
            #getSmsLog,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.SmsLogModel>);

  @override
  _i9.Future<_i2.CheckSmsStatusResponse> checkSmsStatus(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSmsStatus,
          [id],
        ),
        returnValue: _i9.Future<_i2.CheckSmsStatusResponse>.value(
            _FakeCheckSmsStatusResponse_27(
          this,
          Invocation.method(
            #checkSmsStatus,
            [id],
          ),
        )),
      ) as _i9.Future<_i2.CheckSmsStatusResponse>);

  @override
  _i9.Future<_i2.PayFastConfigResponse> getPayFastConfig() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPayFastConfig,
          [],
        ),
        returnValue: _i9.Future<_i2.PayFastConfigResponse>.value(
            _FakePayFastConfigResponse_28(
          this,
          Invocation.method(
            #getPayFastConfig,
            [],
          ),
        )),
      ) as _i9.Future<_i2.PayFastConfigResponse>);

  @override
  _i9.Future<_i2.PushNotificationResponse> sendPushNotification(
          _i2.PushNotificationRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPushNotification,
          [request],
        ),
        returnValue: _i9.Future<_i2.PushNotificationResponse>.value(
            _FakePushNotificationResponse_29(
          this,
          Invocation.method(
            #sendPushNotification,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.PushNotificationResponse>);

  @override
  _i9.Future<_i2.PushNotificationHistoryResponse> getPushNotificationHistory(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPushNotificationHistory,
          [page],
        ),
        returnValue: _i9.Future<_i2.PushNotificationHistoryResponse>.value(
            _FakePushNotificationHistoryResponse_30(
          this,
          Invocation.method(
            #getPushNotificationHistory,
            [page],
          ),
        )),
      ) as _i9.Future<_i2.PushNotificationHistoryResponse>);

  @override
  _i9.Future<_i2.PushNotificationStatsResponse> getPushNotificationStats() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPushNotificationStats,
          [],
        ),
        returnValue: _i9.Future<_i2.PushNotificationStatsResponse>.value(
            _FakePushNotificationStatsResponse_31(
          this,
          Invocation.method(
            #getPushNotificationStats,
            [],
          ),
        )),
      ) as _i9.Future<_i2.PushNotificationStatsResponse>);

  @override
  _i9.Future<List<_i2.EventModel>> getEvents(
    int? municipalityId, {
    bool? upcomingOnly,
    DateTime? dateFrom,
    DateTime? dateTo,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEvents,
          [municipalityId],
          {
            #upcomingOnly: upcomingOnly,
            #dateFrom: dateFrom,
            #dateTo: dateTo,
          },
        ),
        returnValue: _i9.Future<List<_i2.EventModel>>.value(<_i2.EventModel>[]),
      ) as _i9.Future<List<_i2.EventModel>>);

  @override
  _i9.Future<_i2.EventModel> getEventDetail(
    int? municipalityId,
    int? eventId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventDetail,
          [
            municipalityId,
            eventId,
          ],
        ),
        returnValue: _i9.Future<_i2.EventModel>.value(_FakeEventModel_32(
          this,
          Invocation.method(
            #getEventDetail,
            [
              municipalityId,
              eventId,
            ],
          ),
        )),
      ) as _i9.Future<_i2.EventModel>);

  @override
  _i9.Future<_i2.EventRegistrationResponse> submitEventRsvp(
    int? municipalityId,
    int? eventId,
    Map<String, dynamic>? request,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitEventRsvp,
          [
            municipalityId,
            eventId,
            request,
          ],
        ),
        returnValue: _i9.Future<_i2.EventRegistrationResponse>.value(
            _FakeEventRegistrationResponse_33(
          this,
          Invocation.method(
            #submitEventRsvp,
            [
              municipalityId,
              eventId,
              request,
            ],
          ),
        )),
      ) as _i9.Future<_i2.EventRegistrationResponse>);

  @override
  _i9.Future<_i2.FeedbackResponse> submitFeedback(
          _i2.FeedbackRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitFeedback,
          [request],
        ),
        returnValue:
            _i9.Future<_i2.FeedbackResponse>.value(_FakeFeedbackResponse_34(
          this,
          Invocation.method(
            #submitFeedback,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.FeedbackResponse>);

  @override
  _i9.Future<_i2.PaymentResponse> createPayment(_i2.PaymentRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPayment,
          [request],
        ),
        returnValue:
            _i9.Future<_i2.PaymentResponse>.value(_FakePaymentResponse_35(
          this,
          Invocation.method(
            #createPayment,
            [request],
          ),
        )),
      ) as _i9.Future<_i2.PaymentResponse>);

  @override
  _i9.Future<_i2.PaymentResponse> retryPayment(int? paymentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #retryPayment,
          [paymentId],
        ),
        returnValue:
            _i9.Future<_i2.PaymentResponse>.value(_FakePaymentResponse_35(
          this,
          Invocation.method(
            #retryPayment,
            [paymentId],
          ),
        )),
      ) as _i9.Future<_i2.PaymentResponse>);

  @override
  _i9.Future<_i2.PaginatedResponse<_i2.PaymentModel>> getPaymentHistory(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaymentHistory,
          [page],
        ),
        returnValue: _i9.Future<_i2.PaginatedResponse<_i2.PaymentModel>>.value(
            _FakePaginatedResponse_6<_i2.PaymentModel>(
          this,
          Invocation.method(
            #getPaymentHistory,
            [page],
          ),
        )),
      ) as _i9.Future<_i2.PaginatedResponse<_i2.PaymentModel>>);

  @override
  _i9.Future<_i2.MembershipStatusResponse> getMembershipStatus() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMembershipStatus,
          [],
        ),
        returnValue: _i9.Future<_i2.MembershipStatusResponse>.value(
            _FakeMembershipStatusResponse_36(
          this,
          Invocation.method(
            #getMembershipStatus,
            [],
          ),
        )),
      ) as _i9.Future<_i2.MembershipStatusResponse>);
}
