// Mocks generated by Mockito 5.4.4 from annotations
// in ncm_mobile_app/test/features/dashboard/pages/field_worker_dashboard_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ncm_mobile_app/data/models/user_model.dart' as _i8;
import 'package:ncm_mobile_app/data/models/visit_model.dart' as _i3;
import 'package:ncm_mobile_app/providers/auth_provider.dart' as _i7;
import 'package:ncm_mobile_app/providers/visits_provider.dart' as _i4;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAsyncValue_0<T> extends _i1.SmartFake implements _i2.AsyncValue<T> {
  _FakeAsyncValue_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVisitModel_1 extends _i1.SmartFake implements _i3.VisitModel {
  _FakeVisitModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VisitsNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisitsNotifier extends _i1.Mock implements _i4.VisitsNotifier {
  MockVisitsNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i2.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.AsyncValue<List<_i3.VisitModel>>> get stream =>
      (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.AsyncValue<List<_i3.VisitModel>>>.empty(),
      ) as _i5.Stream<_i2.AsyncValue<List<_i3.VisitModel>>>);

  @override
  _i2.AsyncValue<List<_i3.VisitModel>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_0<List<_i3.VisitModel>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<List<_i3.VisitModel>>);

  @override
  set state(_i2.AsyncValue<List<_i3.VisitModel>>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AsyncValue<List<_i3.VisitModel>> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAsyncValue_0<List<_i3.VisitModel>>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.AsyncValue<List<_i3.VisitModel>>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> loadVisits({
    int? fieldWorkerId,
    int? memberId,
    String? visitType,
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadVisits,
          [],
          {
            #fieldWorkerId: fieldWorkerId,
            #memberId: memberId,
            #visitType: visitType,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> assignVisit(
    int? visitId,
    int? leaderId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #assignVisit,
          [
            visitId,
            leaderId,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.VisitModel> checkInToVisit(
    int? visitId, {
    double? latitude,
    double? longitude,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkInToVisit,
          [visitId],
          {
            #latitude: latitude,
            #longitude: longitude,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<_i3.VisitModel>.value(_FakeVisitModel_1(
          this,
          Invocation.method(
            #checkInToVisit,
            [visitId],
            {
              #latitude: latitude,
              #longitude: longitude,
              #notes: notes,
            },
          ),
        )),
      ) as _i5.Future<_i3.VisitModel>);

  @override
  _i5.Future<_i3.VisitModel> checkOutFromVisit(
    int? visitId, {
    double? latitude,
    double? longitude,
    String? notes,
    String? outcome,
    int? sentimentScore,
    String? memberSatisfaction,
    List<String>? issuesIdentified,
    bool? followUpRequired = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkOutFromVisit,
          [visitId],
          {
            #latitude: latitude,
            #longitude: longitude,
            #notes: notes,
            #outcome: outcome,
            #sentimentScore: sentimentScore,
            #memberSatisfaction: memberSatisfaction,
            #issuesIdentified: issuesIdentified,
            #followUpRequired: followUpRequired,
          },
        ),
        returnValue: _i5.Future<_i3.VisitModel>.value(_FakeVisitModel_1(
          this,
          Invocation.method(
            #checkOutFromVisit,
            [visitId],
            {
              #latitude: latitude,
              #longitude: longitude,
              #notes: notes,
              #outcome: outcome,
              #sentimentScore: sentimentScore,
              #memberSatisfaction: memberSatisfaction,
              #issuesIdentified: issuesIdentified,
              #followUpRequired: followUpRequired,
            },
          ),
        )),
      ) as _i5.Future<_i3.VisitModel>);

  @override
  _i5.Future<_i3.VisitModel> createVisit({
    required int? memberId,
    required int? leaderId,
    required String? visitType,
    required DateTime? visitDate,
    String? locationAddress,
    String? status = r'scheduled',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createVisit,
          [],
          {
            #memberId: memberId,
            #leaderId: leaderId,
            #visitType: visitType,
            #visitDate: visitDate,
            #locationAddress: locationAddress,
            #status: status,
          },
        ),
        returnValue: _i5.Future<_i3.VisitModel>.value(_FakeVisitModel_1(
          this,
          Invocation.method(
            #createVisit,
            [],
            {
              #memberId: memberId,
              #leaderId: leaderId,
              #visitType: visitType,
              #visitDate: visitDate,
              #locationAddress: locationAddress,
              #status: status,
            },
          ),
        )),
      ) as _i5.Future<_i3.VisitModel>);

  @override
  _i5.Future<_i3.VisitModel> createQuickVisit({
    required String? name,
    required String? surname,
    String? phoneNumber,
    required String? address,
    required String? visitType,
    required DateTime? visitDate,
    required String? priority,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createQuickVisit,
          [],
          {
            #name: name,
            #surname: surname,
            #phoneNumber: phoneNumber,
            #address: address,
            #visitType: visitType,
            #visitDate: visitDate,
            #priority: priority,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<_i3.VisitModel>.value(_FakeVisitModel_1(
          this,
          Invocation.method(
            #createQuickVisit,
            [],
            {
              #name: name,
              #surname: surname,
              #phoneNumber: phoneNumber,
              #address: address,
              #visitType: visitType,
              #visitDate: visitDate,
              #priority: priority,
              #notes: notes,
            },
          ),
        )),
      ) as _i5.Future<_i3.VisitModel>);

  @override
  List<_i3.VisitModel> getTodayVisits() => (super.noSuchMethod(
        Invocation.method(
          #getTodayVisits,
          [],
        ),
        returnValue: <_i3.VisitModel>[],
      ) as List<_i3.VisitModel>);

  @override
  List<_i3.VisitModel> getScheduledVisits() => (super.noSuchMethod(
        Invocation.method(
          #getScheduledVisits,
          [],
        ),
        returnValue: <_i3.VisitModel>[],
      ) as List<_i3.VisitModel>);

  @override
  List<_i3.VisitModel> getCompletedVisits() => (super.noSuchMethod(
        Invocation.method(
          #getCompletedVisits,
          [],
        ),
        returnValue: <_i3.VisitModel>[],
      ) as List<_i3.VisitModel>);

  @override
  List<_i3.VisitModel> getUnassignedVisits() => (super.noSuchMethod(
        Invocation.method(
          #getUnassignedVisits,
          [],
        ),
        returnValue: <_i3.VisitModel>[],
      ) as List<_i3.VisitModel>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<List<_i3.VisitModel>>? old,
    _i2.AsyncValue<List<_i3.VisitModel>>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.RemoveListener addListener(
    _i6.Listener<_i2.AsyncValue<List<_i3.VisitModel>>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuthNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthNotifier extends _i1.Mock implements _i7.AuthNotifier {
  MockAuthNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
      ) as bool);

  @override
  bool get isMember => (super.noSuchMethod(
        Invocation.getter(#isMember),
        returnValue: false,
      ) as bool);

  @override
  bool get isLeader => (super.noSuchMethod(
        Invocation.getter(#isLeader),
        returnValue: false,
      ) as bool);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
      ) as bool);

  @override
  set onError(_i2.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
      ) as bool);

  @override
  _i5.Stream<_i2.AsyncValue<_i8.UserModel?>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i5.Stream<_i2.AsyncValue<_i8.UserModel?>>.empty(),
      ) as _i5.Stream<_i2.AsyncValue<_i8.UserModel?>>);

  @override
  _i2.AsyncValue<_i8.UserModel?> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAsyncValue_0<_i8.UserModel?>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.AsyncValue<_i8.UserModel?>);

  @override
  set state(_i2.AsyncValue<_i8.UserModel?>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.AsyncValue<_i8.UserModel?> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: _FakeAsyncValue_0<_i8.UserModel?>(
          this,
          Invocation.getter(#debugState),
        ),
      ) as _i2.AsyncValue<_i8.UserModel?>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> login(
    String? email,
    String? password, {
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
          {#rememberMe: rememberMe},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  bool updateShouldNotify(
    _i2.AsyncValue<_i8.UserModel?>? old,
    _i2.AsyncValue<_i8.UserModel?>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.RemoveListener addListener(
    _i6.Listener<_i2.AsyncValue<_i8.UserModel?>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
      ) as _i2.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
